function  naturaOnline(){
    
    return `[
        {
            "image": "https://static.natura.com/cdn/ff/eqygDP9Yrk6wcqO518fAvHttRMFXZiHNiuhCs6UqzDE/1643827883/public/products/102115_1_14.jpg", 
            "nomeProduto": "BB Cream FPS 15 Faces",
            "categoria":"mq",
            "Preco":"29,90",  
            "codigo":"102115",           
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/Ji7qmp",
            "linkPagamento":"https://mpago.la/2spYV7h"},
        {
            "image": "https://static.natura.com/cdn/ff/QiWuy4XMUnQnM7uLrgaQUwj4tftELKHAdavi8c2YFjo/1643826696/public/products/92795_1_12.jpg", 
            "nomeProduto": "Sabonete Mamãe e Bebê",
            "categoria":"in",
            "Preco":"29,90",  
            "codigo":"92795",           
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/GGjLGq",
            "linkPagamento":"https://mpago.la/1J2FrQf"},
        {
            "image": "https://static.natura.com/cdn/ff/GD52GkhgFFclGC9lNoEMaKX-MhOr_26In1JfxzfGXaY/1643735467/public/products/53255_1_44.jpg", 
            "nomeProduto": "Natura Homem Desodorante Colônia",
            "categoria":"ma",
            "Preco":"79,90",  
            "codigo":"53255",           
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/TqMg64",
            "linkPagamento":"https://mpago.la/1KWovMA"},
        {
            "image": "https://static.natura.com/cdn/ff/kxD1A4LhUp7PtwaPceXqglgUH2-om-CfqfFAKtqMjk0/1642996431/public/products/68944_1_30.jpg", 
            "nomeProduto": "Kriska Shock Desodorante Colônia",
            "categoria":"fe",
            "Preco":"63,50",  
            "codigo":"68944",           
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/PPVZXk",
            "linkPagamento":"https://is.gd/TqMg64"},
        {
            "image": "https://static.natura.com/cdn/ff/CC6AbvGfQvRWIbjjIajQuBS-4Zi7bP0HqmSLz8maqkM/1643665811/public/products/71600_1_17.jpg", 
            "nomeProduto": "Biografia Desodorante Colônia Feminino",
            "categoria":"fe",
            "Preco":"82,90",  
            "codigo":"71600",           
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/Fdh5Is",
            "linkPagamento":"https://is.gd/TqMg64"},
        {
            "image": "https://static.natura.com/cdn/ff/Xr_X7DXf0S_4AJxBn0-UauDaVxU5_YwDa59wswpAjqo/1643665838/public/products/43135_1_2.jpg", 
            "nomeProduto": "Una Infinito Deo Parfum",
            "categoria":"fe",
            "Preco":"169,90",  
            "codigo":"43135",           
            "DescontoPorcento":"30",
            "SoHoje": "0",
            "link":"https://is.gd/JOzPmB",
            "linkPagamento":"https://is.gd/TqMg64"},
        {
            "image": "https://static.natura.com/cdn/ff/a4l4Vt4cuv65TE-nuyI7eAIulseQzH9AtJ9sj8tAapk/1643664607/public/products/76421_1_21.jpg", 
            "nomeProduto": "Essencial Deo Parfum Feminino",
            "categoria":"fe",
            "Preco":"124,90",  
            "codigo":"76421",           
            "DescontoPorcento":"30",
            "SoHoje": "0",
            "link":"https://is.gd/2KSw2h",
            "linkPagamento":"https://is.gd/TqMg64"},
        {
            "image": "https://static.natura.com/cdn/ff/xzrGt-DmkOcWgksG-KYjOSNTVJ95bvfXFn2QrcHxxQg/1642996300/public/products/102422_1_2.jpg", 
            "nomeProduto": "Humor Liberta Desodorante Colônia",
            "categoria":"hu",
            "Preco":"83,90",  
            "codigo":"102422",           
            "DescontoPorcento":"30",
            "SoHoje": "0",
            "link":"https://is.gd/6FZhb8",
            "linkPagamento":"https://is.gd/TqMg64"},
        {
            "image": "https://static.natura.com/cdn/ff/cVTmPdxNIk0ytBIzhHwKb5Ifd00aUsw9y2zkCNUBSe4/1642996349/public/products/2791_1_2.jpg", 
            "nomeProduto": "Refil Creme Desodorante Nutritivo para o Corpo Tododia Tâmara e Canela",
            "categoria":"pe",
            "Preco":"22,90",  
            "codigo":"2791",                
            "DescontoPorcento":"30",
            "SoHoje": "0",
            "link":"https://is.gd/TDqhLM",
            "linkPagamento":"https://is.gd/TqMg64"},
        {
            "image": "http://static.natura.com.br/static/www/img/promocoes/16869.jpg", 
            "nomeProduto": "Perfume Natura Ekos Frescor Buriti 150ml",
            "categoria":"fe",
            "Preco":"49,90",
            "codigo":"4545",      
            "DescontoPorcento":"40",
            "SoHoje": "1",
            "link":"https://is.gd/LnGp9c",
            "linkPagamento":"https://is.gd/TqMg64"},
        {
            "image": "https://static.natura.com/cdn/ff/m0QdDCV9ofJv8qiMDjTNqOuzuKxqinnQk8KThaPFRuU/1643735477/public/products/76420_1_2.jpg", 
            "nomeProduto": "Essencial Deo Parfum Masculino",
            "categoria":"ma",
            "Preco":"124,90",
            "codigo":"5544",      
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/VOn5Wr",
            "linkPagamento":"https://is.gd/TqMg64"},
        {
            "image": "https://static.natura.com/cdn/ff/WPX9yTbz-vx_BNQC-yFLozbpngNsDWcnaPLzRnSz-AI/1643735433/public/products/22557_1_3.jpg", 
            "nomeProduto": "Kaiak Aventura Desodorante Colônia Masculino",
            "categoria":"ma",
            "Preco":"63,45",
            "codigo":"22557",      
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/67Nx9n",
            "linkPagamento":"https://is.gd/TqMg64"}
]`
;


}