function  naturaOnline(){
    
    return `[
        {   
            "image": "https://rogresph.sirv.com/Naturfive/CDN%20Sirv/varios-produtos-natura.jpeg", 
            "nomeProduto": "Gostaria de ver o catálogo Natura Online",
            "categoria":"catálago",
            "Preco":"0,00",  
            "codigo":"Produtos variados",      
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/desodorante-colonia-kaiak-oceano-masculino-100ml/96493",    
            "DescontoPorcento":"20",
            "SoHoje": "1",
            "link":"https://natura.com.vc/03_co_mg-nqs7x",
            "linkPagamento":"https://natura.com.vc/03_co_mg-nqs7x",
            "txMercadolivre":"6,23"
        },
        {   
            "image": "/imagem-produtos/creme-de-pele-min-100383.jpeg", 
            "nomeProduto": "Refil Creme Desodorante Nutritivo Para o Corpo Tododia Ameixa e Flor de Baunilha",
            "categoria":"co",
            "Preco":"21,50",  
            "codigo":"100383 - Refil Creme Desodorante Nutritivo Para o Corpo Tododia Ameixa e Flor de Baunilha - 400 ml",      
            "linkProdutoSiteNatura": "https://www.natura.com.br/c/tudo-em-corpo-e-banho",    
            "DescontoPorcento":"35",
            "SoHoje": "1",
            "link":"https://www.natura.com.br/c/tudo-em-corpo-e-banho?consultoria=naturfive",
            "linkPagamento":"https://www.natura.com.br/c/tudo-em-corpo-e-banho?consultoria=naturfive",
            "txMercadolivre":"6,23"
        },
        {   
            "image": "https://rogresph.sirv.com/Naturfive/CDN%20Sirv/natura-tododia-cereja-min-99137_1_14.jpeg", 
            "nomeProduto": "Creme Nutritivo Para o Corpo Tododia Cereja e Avelã",
            "categoria":"co",
            "Preco":"35,00",  
            "codigo":"99137 - Creme Desodorante Nutritivo Para o Corpo Tododia Cereja e Avelã - 400 ml",      
            "linkProdutoSiteNatura": "https://www.natura.com.br/c/tudo-em-corpo-e-banho",    
            "DescontoPorcento":"35",
            "SoHoje": "1",
            "link":"https://www.natura.com.br/p/creme-desodorante-nutritivo-para-o-corpo-tododia-cereja-e-avela-400-ml/99137?consultoria=naturfive",
            "linkPagamento":"https://www.natura.com.br/p/creme-desodorante-nutritivo-para-o-corpo-tododia-cereja-e-avela-400-ml/99137?consultoria=naturfive",
            "txMercadolivre":"6,23"
        },
        {   
            "image": "https://rogresph.sirv.com/Naturfive/CDN%20Sirv/seve-amendoas-intensa-200-ml-natura-desconto-38854.jpeg", 
            "nomeProduto": "Óleo Desodorante Corporal Sève Amêndoas Doces Intensa",
            "categoria":"co",
            "Preco":"34,70",  
            "codigo":"638854 - Óleo Desodorante Corporal Sève Amêndoas Doces Intensa - 200 ml",      
            "linkProdutoSiteNatura": "https://www.natura.com.br/c/tudo-em-corpo-e-banho",    
            "DescontoPorcento":"35",
            "SoHoje": "1",
            "link":"https://www.natura.com.br/p/oleo-desodorante-corporal-seve-amendoas-doces-intensa-200-ml/38854?consultoria=naturfive",
            "linkPagamento":"https://www.natura.com.br/p/oleo-desodorante-corporal-seve-amendoas-doces-intensa-200-ml/38854?consultoria=naturfive",
            "txMercadolivre":"6,23"
        },
        {   
            "image": "https://rogresph.sirv.com/Naturfive/CDN%20Sirv/68542.jpeg", 
            "nomeProduto": "Fluido Multiprotetor FPS 50 / FPUVA 18 Chronos",
            "categoria":"co",
            "Preco":"84,50",  
            "codigo":"68542 - Fluido Multiprotetor FPS 50 / FPUVA 18 Chronos - 50ml",      
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/fluido-multiprotetor-fps-50-fpuva-18-chronos-50ml/68542",    
            "DescontoPorcento":"35",
            "SoHoje": "1",
            "link":"https://www.natura.com.br/p/fluido-multiprotetor-fps-50-fpuva-18-chronos-50ml/68542?consultoria=naturfive",
            "linkPagamento":"https://www.natura.com.br/p/fluido-multiprotetor-fps-50-fpuva-18-chronos-50ml/68542?consultoria=naturfive",
            "txMercadolivre":"6,23"
        },
        {   
            "image": "https://rogresph.sirv.com/Naturfive/CDN%20Sirv/47421.jpeg", 
            "nomeProduto": "Gel Creme Protetor Facial FPS 60/ FPUVA 20",
            "categoria":"co",
            "Preco":"44,90",  
            "codigo":"47421 - Gel Creme Protetor Facial FPS 60/ FPUVA 20 Pele Mista a Oleosa Fotoequilíbrio - 50g",      
            "linkProdutoSiteNatura": "https://www.natura.com.br/c/tudo-em-corpo-e-banho",    
            "DescontoPorcento":"35",
            "SoHoje": "1",
            "link":"https://www.natura.com.br/p/gel-creme-protetor-facial-fps-60-fpuva-20-pele-mista-a-oleosa-fotoequilibrio-50g/47421?consultoria=naturfive",
            "linkPagamento":"https://www.natura.com.br/p/gel-creme-protetor-facial-fps-60-fpuva-20-pele-mista-a-oleosa-fotoequilibrio-50g/47421?consultoria=naturfive",
            "txMercadolivre":"6,23"
        },
         {
            
            "image": "https://rogresph.sirv.com/Naturfive/CDN%20Sirv/115762.jpeg", 
            "nomeProduto": "Combo Mamãe e Bebê Cabelos Com Cheirinho De Cuidado",
            "categoria":"in",
            "Preco":"51,80",  
            "codigo":"115762 - Combo Mamãe e Bebê Cabelos Com Cheirinho De Cuidado",  
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/combo-mamae-e-bebe-cabelos-com-cheirinho-de-cuidado/115762",          
            "DescontoPorcento":"35",
            "SoHoje": "1",
            "link":"https://is.gd/sRFZho",
            "linkPagamento":"https://www.natura.com.br/p/combo-mamae-e-bebe-cabelos-com-cheirinho-de-cuidado/115762?consultoria=naturfive",
            "txMercadolivre":"https://www.natura.com.br/p/combo-mamae-e-bebe-cabelos-com-cheirinho-de-cuidado/115762?consultoria=naturfive"
        },    
        {
            
            "image": "https://static.natura.com/cdn/ff/uyHNOvw7Nmk7a0pTbdyAYs7jVm_aXHqNsDKJWodaliE/1645638010/public/products/102419_1_2.jpg", 
            "nomeProduto": "Ilía Ser Deo Parfum",
            "categoria":"fe",
            "Preco":"99,90",  
            "codigo":"102419 - Ilía Ser Deo Parfum - 50 ml",  
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/ilia-ser-deo-parfum-50-ml/102419",          
            "DescontoPorcento":"35",
            "SoHoje": "1",
            "link":"https://is.gd/sRFZho",
            "linkPagamento":"https://www.natura.com.br/p/ilia-ser-deo-parfum-50-ml/102419?consultoria=naturfive",
            "txMercadolivre":"https://www.natura.com.br/p/ilia-ser-deo-parfum-50-ml/102419?consultoria=naturfive"
        },    
        {
            
            "image": "https://static.natura.com/cdn/ff/MlE3XxuObJTuag_JtldCgOF_ZbTd8wrz4lF9u3jNagY/1645651293/public/products/54522_1_22.jpg", 
            "nomeProduto": "Ilía Deo Parfum",
            "categoria":"fe",
            "Preco":"99,90",  
            "codigo":"54522 - Ilía - 50 ml",  
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/ilia-50-ml/54522",          
            "DescontoPorcento":"35",
            "SoHoje": "1",
            "link":"https://is.gd/sRFZho",
            "linkPagamento":"https://www.natura.com.br/p/ilia-50-ml/54522?consultoria=naturfive",
            "txMercadolivre":"https://www.natura.com.br/p/ilia-50-ml/54522?consultoria=naturfive"
        },
        {
            
            "image": "https://static.natura.com/cdn/ff/A8ksPWDBESBxqCckpBc87x44Nw-K9fYhVVB5DOEYK5k/1645638607/public/products/103348_1_2.jpg", 
            "nomeProduto": "Essencial Único Deo Parfum Masculino",
            "categoria":"ma",
            "Preco":"174,90",  
            "codigo":"103348 - Essencial Único Deo Parfum Masculino - 90 ml",  
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/essencial-unico-deo-parfum-masculino-90-ml/103348",          
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/sRFZho",
            "linkPagamento":"https://www.natura.com.br/p/essencial-unico-deo-parfum-masculino-90-ml/103348?&consultoria=naturfive",
            "txMercadolivre":"https://www.natura.com.br/p/essencial-unico-deo-parfum-masculino-90-ml/103348?&consultoria=naturfive"
        },

        {
            
            "image": "https://static.natura.com/cdn/ff/JZqu-Xmrci5JQfy412UzqhcviYq8h-A1bEzVjqFMSeY/1644877887/public/products/96711_1_2.jpg", 
            "nomeProduto": "Kaiak Oceano Desodorante Colônia Feminino",
            "categoria":"fe",
            "Preco":"84,90",  
            "codigo":"96711 - Desodorante Colônia Kaiak Oceano Feminino - 100ml",  
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/desodorante-colonia-kaiak-oceano-masculino-100ml/96493",          
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/sRFZho",
            "linkPagamento":"https://mpago.la/31R43QM",
            "txMercadolivre":"https://www.natura.com.br/p/desodorante-colonia-kaiak-oceano-feminino-100ml/96711?listTitle=manual%20showcase%20-%20garanta%20sua%20fragr%C3%A2ncia%20favorita&list_position=3&consultoria=naturfive"
        },
            
        {
            
            "image": "https://rogresph.sirv.com/Naturfive/CDN%20Sirv/57525.jpeg", 
            "nomeProduto": "K Deo Parfum Masculino",
            "categoria":"ma",
            "Preco":"157,90",  
            "codigo":"57525 - K - 100 ml",    
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/k-100-ml/57525",       
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/Jxbm3G",
            "linkPagamento":"https://mpago.la/1KBgKjB",
            "txMercadolivre":"https://www.natura.com.br/p/k-100-ml/57525?listTitle=manual%20showcase%20-%20novidades%20e%20ofertas%20imperd%C3%ADveis%20%F0%9F%91%87&list_position=6&consultoria=naturfive"},
        {
            
            "image": "https://static.natura.com/cdn/ff/upapSeMD4oL6MDdr6_xJ6R1Kq8fSnt3wM3W9v19K7xg/1644238858/public/products/59313_1_14.jpg", 
            "nomeProduto": "Primer Blur Una",
            "categoria":"mq",
            "Preco":"52,90",  
            "codigo":"59313 - Primer Blur Una - 30 ml", 
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/primer-blur-una-30-ml/59313",          
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/F4TfIW",
            "linkPagamento":"https://mpago.la/2gecLzp",
            "txMercadolivre":"2,64"},
        {
            
            "image": "./imagem-produtos/essencial-oud-deo-76424_1_26.jpg", 
            "nomeProduto": "Essencial Oud Deo Parfum Masculino",
            "categoria":"ma",
            "Preco":"124,90",  
            "codigo":"76424 - Essencial Oud Masculino - 100 ml",   
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/essencial-oud-masculino-100-ml/76424",        
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/I8rQyJ",
            "linkPagamento":"https://mpago.la/2cPA8tD",
            "txMercadolivre":"6,23"},
        {
            "image": "https://rogresph.sirv.com/Naturfive/CDN%20Sirv/25227.jpeg", 
            "nomeProduto": "Kit Kaiak Pulso Desodorante Colônia Masculino",
            "categoria":"ma",
            "Preco":"134,90",  
            "codigo":"115901 - Kit Kaiak Pulso Desodorante Colônia Masculino",  
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/kaiak-pulso-masculino-100-ml/25227",         
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/OtQ4dW",
            "linkPagamento":"https://mpago.la/2STnLo1",
            "txMercadolivre":"6,73"},
        {
            "image": "https://static.natura.com/cdn/ff/eqygDP9Yrk6wcqO518fAvHttRMFXZiHNiuhCs6UqzDE/1643827883/public/products/102115_1_14.jpg", 
            "nomeProduto": "BB Cream FPS 15 Faces",
            "categoria":"mq",
            "Preco":"29,90",  
            "codigo":"102115",           
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/bb-cream-fps-15-faces-20-g/102115",
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/Ji7qmp",
            "linkPagamento":"https://mpago.la/2spYV7h",
            "txMercadolivre":"3,24"},
        {
            "image": "https://rogresph.sirv.com/Naturfive/CDN%20Sirv/92795.jpeg", 
            "nomeProduto": "Sabonete Mamãe e Bebê",
            "categoria":"in",
            "Preco":"29,90",  
            "codigo":"92795",           
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/sabonete-mamae-e-bebe-5-un-de-100-g-cada/92795",
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/GGjLGq",
            "linkPagamento":"https://mpago.la/1J2FrQf",
            "txMercadolivre":"3,24"},
        {
            "image": "https://rogresph.sirv.com/Naturfive/CDN%20Sirv/53255.jpeg", 
            "nomeProduto": "Natura Homem Desodorante Colônia",
            "categoria":"ma",
            "Preco":"79,90",  
            "codigo":"53255",           
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/desodorante-colonia-natura-homem-100-ml/53255",
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/TqMg64",
            "linkPagamento":"https://mpago.la/1KWovMA",
            "txMercadolivre":"3,24"},
        {
            "image": "https://rogresph.sirv.com/Naturfive/CDN%20Sirv/68944.jpeg", 
            "nomeProduto": "Kriska Shock Desodorante Colônia",
            "categoria":"fe",
            "Preco":"63,50",  
            "codigo":"68944 - Kriska Shock Desodorante Colônia - 100 ml",      
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/kriska-shock-desodorante-colonia-100-ml/68944",     
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/Kx2bWO",
            "linkPagamento":"https://mpago.la/1fKJHVY",
            "txMercadolivre":"3,17"},
        {
            "image": "https://rogresph.sirv.com/Naturfive/CDN%20Sirv/71600.jpeg", 
            "nomeProduto": "Biografia Desodorante Colônia Feminino",
            "categoria":"fe",
            "Preco":"82,90",  
            "codigo":"71600 - Biografia Desodorante Colônia Feminino - 100 ml",       
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/biografia-desodorante-colonia-feminino-100-ml/71600",    
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/OM0niP",
            "linkPagamento":"https://mpago.la/2k317ho",
            "txMercadolivre":"4,14"},
        {
            "image": "https://static.natura.com/cdn/ff/Xr_X7DXf0S_4AJxBn0-UauDaVxU5_YwDa59wswpAjqo/1643665838/public/products/43135_1_2.jpg", 
            "nomeProduto": "Una Infinito Deo Parfum",
            "categoria":"fe",
            "Preco":"169,90",  
            "codigo":"43135 - Una Infinito Deo Parfum - 75 ml",    
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/una-esmalte-cor-orbita-8-ml/93790",       
            "DescontoPorcento":"30",
            "SoHoje": "0",
            "link":"https://is.gd/JOzPmB",
            "linkPagamento":"https://mpago.la/12qQYmX",
            "txMercadolivre":"8,48"},
        {
            "image": "https://rogresph.sirv.com/Naturfive/CDN%20Sirv/76421.jpeg", 
            "nomeProduto": "Essencial Deo Parfum Feminino - Essencial",
            "categoria":"fe",
            "Preco":"124,90",  
            "codigo":"76421 - Essencial Feminino - 100 ml",           
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/essencial-feminino-100-ml/76421",
            "DescontoPorcento":"30",
            "SoHoje": "0",
            "link":"https://is.gd/2KSw2h",
            "linkPagamento":"https://mpago.la/2msTEJE",
            "txMercadolivre":"6,24"},
        {
            "image": "https://rogresph.sirv.com/Naturfive/CDN%20Sirv/102422.jpeg", 
            "nomeProduto": "Humor Liberta Desodorante Colônia",
            "categoria":"hu",
            "Preco":"83,90",  
            "codigo":"102422 - Humor Liberta Desodorante Colônia - 75 ml",   
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/humor-liberta-desodorante-colonia-75-ml/102422",        
            "DescontoPorcento":"30",
            "SoHoje": "0",
            "link":"https://is.gd/6FZhb8",
            "linkPagamento":"https://mpago.la/1vQSZEK",
            "txMercadolivre":"4,15"},
        {
            "image": "https://rogresph.sirv.com/Naturfive/CDN%20Sirv/56417.jpeg", 
            "nomeProduto": "Luna Absoluta Desodorante Colônia",
            "categoria":"pe",
            "Preco":"79,90",  
            "codigo":"56417 - Luna Absoluta Desodorante Colônia - 75 ml",     
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/luna-absoluta-desodorante-colonia-75-ml/56417",           
            "DescontoPorcento":"30",
            "SoHoje": "0",
            "link":"https://is.gd/TDqhLM",
            "linkPagamento":"https://mpago.la/2V6gtc2",
            "txMercadolivre":"3,99"},
        {
            "image": "https://rogresph.sirv.com/Naturfive/CDN%20Sirv/86723.jpeg", 
            "nomeProduto": "Meu Primeiro Humor Desodorante Colônia",
            "categoria":"pe",
            "Preco":"64,90",
            "codigo":"86723 - Meu Primeiro Humor - 75 ml",      
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/meu-primeiro-humor-75-ml/86723",
            "DescontoPorcento":"40",
            "SoHoje": "1",
            "link":"https://is.gd/HMUiqo",
            "linkPagamento":"https://mpago.la/1AQ8t5g",
            "txMercadolivre":"3,24"},
        {
            "image": "https://rogresph.sirv.com/Naturfive/CDN%20Sirv/76420.jpeg", 
            "nomeProduto": "Essencial Deo Parfum Masculino",
            "categoria":"ma",
            "Preco":"124,90",
            "codigo":"76420",      
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/essencial-masculino-100-ml/76420",
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/VOn5Wr",
            "linkPagamento":"https://mpago.la/2uTZFYV",
            "txMercadolivre":"3,24"},
        {
            "image": "/imagem-produtos/kaik-aventura-natura-min-22557.jpeg", 
            "nomeProduto": "Kaiak Aventura Desodorante Colônia Masculino",
            "categoria":"ma",
            "Preco":"63,45",
            "codigo":"22557",      
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/kaiak-aventura-masculino-100-ml/22557",
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/67Nx9n",
            "linkPagamento":"https://mpago.la/1pFvsUA",
            "txMercadolivre":"3,24"}
]`
;


}