function  naturaOnline(){
    // https://cf.shopee.com.br/file/ad1241042e1c6cfd0901f44841174d03
    return `[
        {   
            "image": "/natura-img/ab.jpeg", 
            "nomeProduto": "Gostaria de ver o catálogo Natura Online",
            "categoria":"catálago",
            "Preco":"0,00",  
            "codigo":"Produtos variados",      
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/desodorante-colonia-kaiak-oceano-masculino-100ml/96493",    
            "DescontoPorcento":"20",
            "SoHoje": "1",
            "link":"https://natura.com.vc/03_co_mg-nqs7x",
            "linkPagamento":"https://natura.com.vc/03_co_mg-nqs7x",
            "txMercadolivre":"6,23"},
         {
            
            "image": "https://static.natura.com/cdn/ff/1NmC2BB2RMBqEVj74XHoklpfS3O5jb7Q931rUX4Mav4/1645621227/public/products/115762_1_8.jpg", 
            "nomeProduto": "Combo Mamãe e Bebê Cabelos Com Cheirinho De Cuidado",
            "categoria":"in",
            "Preco":"51,80",  
            "codigo":"115762 - Combo Mamãe e Bebê Cabelos Com Cheirinho De Cuidado",  
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/combo-mamae-e-bebe-cabelos-com-cheirinho-de-cuidado/115762",          
            "DescontoPorcento":"35",
            "SoHoje": "1",
            "link":"https://is.gd/sRFZho",
            "linkPagamento":"https://www.natura.com.br/p/combo-mamae-e-bebe-cabelos-com-cheirinho-de-cuidado/115762?consultoria=naturfive",
            "txMercadolivre":"https://www.natura.com.br/p/combo-mamae-e-bebe-cabelos-com-cheirinho-de-cuidado/115762?consultoria=naturfive"
        },    
        {
            
            "image": "https://static.natura.com/cdn/ff/uyHNOvw7Nmk7a0pTbdyAYs7jVm_aXHqNsDKJWodaliE/1645638010/public/products/102419_1_2.jpg", 
            "nomeProduto": "Ilía Ser Deo Parfum",
            "categoria":"fe",
            "Preco":"99,90",  
            "codigo":"102419 - Ilía Ser Deo Parfum - 50 ml",  
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/ilia-ser-deo-parfum-50-ml/102419",          
            "DescontoPorcento":"35",
            "SoHoje": "1",
            "link":"https://is.gd/sRFZho",
            "linkPagamento":"https://www.natura.com.br/p/ilia-ser-deo-parfum-50-ml/102419?consultoria=naturfive",
            "txMercadolivre":"https://www.natura.com.br/p/ilia-ser-deo-parfum-50-ml/102419?consultoria=naturfive"
        },    
        {
            
            "image": "https://static.natura.com/cdn/ff/MlE3XxuObJTuag_JtldCgOF_ZbTd8wrz4lF9u3jNagY/1645651293/public/products/54522_1_22.jpg", 
            "nomeProduto": "Ilía Deo Parfum",
            "categoria":"fe",
            "Preco":"99,90",  
            "codigo":"54522 - Ilía - 50 ml",  
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/ilia-50-ml/54522",          
            "DescontoPorcento":"35",
            "SoHoje": "1",
            "link":"https://is.gd/sRFZho",
            "linkPagamento":"https://www.natura.com.br/p/ilia-50-ml/54522?consultoria=naturfive",
            "txMercadolivre":"https://www.natura.com.br/p/ilia-50-ml/54522?consultoria=naturfive"
        },
        {
            
            "image": "https://static.natura.com/cdn/ff/A8ksPWDBESBxqCckpBc87x44Nw-K9fYhVVB5DOEYK5k/1645638607/public/products/103348_1_2.jpg", 
            "nomeProduto": "Essencial Único Deo Parfum Masculino",
            "categoria":"ma",
            "Preco":"174,90",  
            "codigo":"103348 - Essencial Único Deo Parfum Masculino - 90 ml",  
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/essencial-unico-deo-parfum-masculino-90-ml/103348",          
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/sRFZho",
            "linkPagamento":"https://www.natura.com.br/p/essencial-unico-deo-parfum-masculino-90-ml/103348?&consultoria=naturfive",
            "txMercadolivre":"https://www.natura.com.br/p/essencial-unico-deo-parfum-masculino-90-ml/103348?&consultoria=naturfive"
        },

        {
            
            "image": "https://static.natura.com/cdn/ff/JZqu-Xmrci5JQfy412UzqhcviYq8h-A1bEzVjqFMSeY/1644877887/public/products/96711_1_2.jpg", 
            "nomeProduto": "Kaiak Oceano Desodorante Colônia Feminino",
            "categoria":"fe",
            "Preco":"84,90",  
            "codigo":"96711 - Desodorante Colônia Kaiak Oceano Feminino - 100ml",  
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/desodorante-colonia-kaiak-oceano-masculino-100ml/96493",          
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/sRFZho",
            "linkPagamento":"https://mpago.la/31R43QM",
            "txMercadolivre":"https://www.natura.com.br/p/desodorante-colonia-kaiak-oceano-feminino-100ml/96711?listTitle=manual%20showcase%20-%20garanta%20sua%20fragr%C3%A2ncia%20favorita&list_position=3&consultoria=naturfive"
        },
            
        {
            
            "image": "https://static.natura.com/cdn/ff/DMc1L9rvvEKEaDSloPmferMjQItQDIy6gLtaAni4WBc/1644278436/public/products/57525_1_13.jpg", 
            "nomeProduto": "K Deo Parfum Masculino",
            "categoria":"ma",
            "Preco":"157,90",  
            "codigo":"57525 - K - 100 ml",    
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/k-100-ml/57525",       
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/Jxbm3G",
            "linkPagamento":"https://mpago.la/1KBgKjB",
            "txMercadolivre":"https://www.natura.com.br/p/k-100-ml/57525?listTitle=manual%20showcase%20-%20novidades%20e%20ofertas%20imperd%C3%ADveis%20%F0%9F%91%87&list_position=6&consultoria=naturfive"},
        {
            
            "image": "https://static.natura.com/cdn/ff/upapSeMD4oL6MDdr6_xJ6R1Kq8fSnt3wM3W9v19K7xg/1644238858/public/products/59313_1_14.jpg", 
            "nomeProduto": "Primer Blur Una",
            "categoria":"mq",
            "Preco":"52,90",  
            "codigo":"59313 - Primer Blur Una - 30 ml", 
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/primer-blur-una-30-ml/59313",          
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/F4TfIW",
            "linkPagamento":"https://mpago.la/2gecLzp",
            "txMercadolivre":"2,64"},
        {
            
            "image": "https://static.natura.com/cdn/ff/3K7paEnoz67u6An0h7FOy_Cacytp9F7GbjFFOEt_eD8/1643897475/public/products/76424_1_20.jpg", 
            "nomeProduto": "Essencial Oud Deo Parfum Masculino",
            "categoria":"ma",
            "Preco":"124,90",  
            "codigo":"76424 - Essencial Oud Masculino - 100 ml",   
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/essencial-oud-masculino-100-ml/76424",        
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/I8rQyJ",
            "linkPagamento":"https://mpago.la/2cPA8tD",
            "txMercadolivre":"6,23"},
        {
            "image": "https://static.natura.com/cdn/ff/bqrqLohLdCD_2p9ZhanM6yKDR6z2YH3bV9Oc-3FCx4Q/1643905204/public/products/115901_1_2.jpg", 
            "nomeProduto": "Kit Kaiak Pulso Desodorante Colônia Masculino",
            "categoria":"ma",
            "Preco":"134,90",  
            "codigo":"115901 - Kit Kaiak Pulso Desodorante Colônia Masculino",  
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/kit-kaiak-pulso-desodorante-colonia-masculino/115901",         
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/OtQ4dW",
            "linkPagamento":"https://mpago.la/2STnLo1",
            "txMercadolivre":"6,73"},
        {
            "image": "https://static.natura.com/cdn/ff/eqygDP9Yrk6wcqO518fAvHttRMFXZiHNiuhCs6UqzDE/1643827883/public/products/102115_1_14.jpg", 
            "nomeProduto": "BB Cream FPS 15 Faces",
            "categoria":"mq",
            "Preco":"29,90",  
            "codigo":"102115",           
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/bb-cream-fps-15-faces-20-g/102115",
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/Ji7qmp",
            "linkPagamento":"https://mpago.la/2spYV7h",
            "txMercadolivre":"3,24"},
        {
            "image": "https://static.natura.com/cdn/ff/QiWuy4XMUnQnM7uLrgaQUwj4tftELKHAdavi8c2YFjo/1643826696/public/products/92795_1_12.jpg", 
            "nomeProduto": "Sabonete Mamãe e Bebê",
            "categoria":"in",
            "Preco":"29,90",  
            "codigo":"92795",           
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/sabonete-mamae-e-bebe-5-un-de-100-g-cada/92795",
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/GGjLGq",
            "linkPagamento":"https://mpago.la/1J2FrQf",
            "txMercadolivre":"3,24"},
        {
            "image": "https://static.natura.com/cdn/ff/GD52GkhgFFclGC9lNoEMaKX-MhOr_26In1JfxzfGXaY/1643735467/public/products/53255_1_44.jpg", 
            "nomeProduto": "Natura Homem Desodorante Colônia",
            "categoria":"ma",
            "Preco":"79,90",  
            "codigo":"53255",           
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/desodorante-colonia-natura-homem-100-ml/53255",
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/TqMg64",
            "linkPagamento":"https://mpago.la/1KWovMA",
            "txMercadolivre":"3,24"},
        {
            "image": "https://static.natura.com/cdn/ff/kxD1A4LhUp7PtwaPceXqglgUH2-om-CfqfFAKtqMjk0/1642996431/public/products/68944_1_30.jpg", 
            "nomeProduto": "Kriska Shock Desodorante Colônia",
            "categoria":"fe",
            "Preco":"63,50",  
            "codigo":"68944 - Kriska Shock Desodorante Colônia - 100 ml",      
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/kriska-shock-desodorante-colonia-100-ml/68944",     
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/Kx2bWO",
            "linkPagamento":"https://mpago.la/1fKJHVY",
            "txMercadolivre":"3,17"},
        {
            "image": "https://static.natura.com/cdn/ff/CC6AbvGfQvRWIbjjIajQuBS-4Zi7bP0HqmSLz8maqkM/1643665811/public/products/71600_1_17.jpg", 
            "nomeProduto": "Biografia Desodorante Colônia Feminino",
            "categoria":"fe",
            "Preco":"82,90",  
            "codigo":"71600 - Biografia Desodorante Colônia Feminino - 100 ml",       
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/biografia-desodorante-colonia-feminino-100-ml/71600",    
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/OM0niP",
            "linkPagamento":"https://mpago.la/2k317ho",
            "txMercadolivre":"4,14"},
        {
            "image": "https://static.natura.com/cdn/ff/Xr_X7DXf0S_4AJxBn0-UauDaVxU5_YwDa59wswpAjqo/1643665838/public/products/43135_1_2.jpg", 
            "nomeProduto": "Una Infinito Deo Parfum",
            "categoria":"fe",
            "Preco":"169,90",  
            "codigo":"43135 - Una Infinito Deo Parfum - 75 ml",    
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/una-esmalte-cor-orbita-8-ml/93790",       
            "DescontoPorcento":"30",
            "SoHoje": "0",
            "link":"https://is.gd/JOzPmB",
            "linkPagamento":"https://mpago.la/12qQYmX",
            "txMercadolivre":"8,48"},
        {
            "image": "https://static.natura.com/cdn/ff/a4l4Vt4cuv65TE-nuyI7eAIulseQzH9AtJ9sj8tAapk/1643664607/public/products/76421_1_21.jpg", 
            "nomeProduto": "Essencial Deo Parfum Feminino - Essencial",
            "categoria":"fe",
            "Preco":"124,90",  
            "codigo":"76421 - Essencial Feminino - 100 ml",           
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/essencial-feminino-100-ml/76421",
            "DescontoPorcento":"30",
            "SoHoje": "0",
            "link":"https://is.gd/2KSw2h",
            "linkPagamento":"https://mpago.la/2msTEJE",
            "txMercadolivre":"6,24"},
        {
            "image": "https://static.natura.com/cdn/ff/xzrGt-DmkOcWgksG-KYjOSNTVJ95bvfXFn2QrcHxxQg/1642996300/public/products/102422_1_2.jpg", 
            "nomeProduto": "Humor Liberta Desodorante Colônia",
            "categoria":"hu",
            "Preco":"83,90",  
            "codigo":"102422 - Humor Liberta Desodorante Colônia - 75 ml",   
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/humor-liberta-desodorante-colonia-75-ml/102422",        
            "DescontoPorcento":"30",
            "SoHoje": "0",
            "link":"https://is.gd/6FZhb8",
            "linkPagamento":"https://mpago.la/1vQSZEK",
            "txMercadolivre":"4,15"},
        {
            "image": "https://static.natura.com/cdn/ff/6X8d-OgQlyZTA3T4WKCMpepBvLnjDWqEx4IMv9t2oUE/1643893829/public/products/56417_1_13.jpg", 
            "nomeProduto": "Luna Absoluta Desodorante Colônia",
            "categoria":"pe",
            "Preco":"79,90",  
            "codigo":"56417 - Luna Absoluta Desodorante Colônia - 75 ml",     
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/luna-absoluta-desodorante-colonia-75-ml/56417",           
            "DescontoPorcento":"30",
            "SoHoje": "0",
            "link":"https://is.gd/TDqhLM",
            "linkPagamento":"https://mpago.la/2V6gtc2",
            "txMercadolivre":"3,99"},
        {
            "image": "https://static.natura.com/cdn/ff/90t5W6O8x9RYQKW8jaXk5XcES0dsmBeYzJez3krCozA/1643896275/public/products/86723_1_22.jpg", 
            "nomeProduto": "Meu Primeiro Humor Desodorante Colônia",
            "categoria":"pe",
            "Preco":"64,90",
            "codigo":"86723 - Meu Primeiro Humor - 75 ml",      
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/meu-primeiro-humor-75-ml/86723",
            "DescontoPorcento":"40",
            "SoHoje": "1",
            "link":"https://is.gd/HMUiqo",
            "linkPagamento":"https://mpago.la/1AQ8t5g",
            "txMercadolivre":"3,24"},
        {
            "image": "https://static.natura.com/cdn/ff/m0QdDCV9ofJv8qiMDjTNqOuzuKxqinnQk8KThaPFRuU/1643735477/public/products/76420_1_2.jpg", 
            "nomeProduto": "Essencial Deo Parfum Masculino",
            "categoria":"ma",
            "Preco":"124,90",
            "codigo":"5544",      
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/essencial-masculino-100-ml/76420",
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/VOn5Wr",
            "linkPagamento":"https://mpago.la/2uTZFYV",
            "txMercadolivre":"3,24"},
        {
            "image": "https://static.natura.com/cdn/ff/WPX9yTbz-vx_BNQC-yFLozbpngNsDWcnaPLzRnSz-AI/1643735433/public/products/22557_1_3.jpg", 
            "nomeProduto": "Kaiak Aventura Desodorante Colônia Masculino",
            "categoria":"ma",
            "Preco":"63,45",
            "codigo":"22557",      
            "linkProdutoSiteNatura": "https://www.natura.com.br/p/kaiak-aventura-masculino-100-ml/22557",
            "DescontoPorcento":"30",
            "SoHoje": "1",
            "link":"https://is.gd/67Nx9n",
            "linkPagamento":"https://mpago.la/1pFvsUA",
            "txMercadolivre":"3,24"}
]`
;


}